"""Add user_id column to contacts

Revision ID: 9339a9e17423
Revises: c0ac7a6f61b2
Create Date: 2025-02-05 20:16:48.855593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9339a9e17423'
down_revision: Union[str, None] = 'c0ac7a6f61b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
